// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://rchjjagmmnidkgzzmusp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjaGpqYWdtbW5pZGtnenptdXNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1NDUxNjEsImV4cCI6MjA3ODEyMTE2MX0.ZMGZFPahMW5O0Cty-K-GkVVVU_8fGfmr1ZRENLIBGx8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);